os: windows
language: dart
dart:
  - stable

intsall:
  - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'

before-install:
  - git clone https://github.com/flutter/flutter.git -b stable

script:
  - PowerShell -File install-flutter.ps1
