image:
  - Visual Studio 2019
  - macOS

for:
  - matrix:
      only:
        - image: Visual Studio 2019
    build_script:
      - cmd: git clone https://github.com/flutter/flutter.git -b stable
      - cmd: ./flutter/bin/flutter channel master
      - cmd: ./flutter/bin/flutter upgrade
      - cmd: ./flutter/bin/flutter config --enable-windows-desktop
      - cmd: ./flutter/bin/flutter doctor
      - cmd: ./flutter/bin/flutter build windows
      - cmd: choco install advanced-installer
      - cmd: cd C:\Program Files (x86)\Caphyon\Advanced Installer 17.0\bin
      - cmd: dir
      - cmd: advanced-installer
#      - cmd: dir /s
  - matrix:
      only:
        - image: macOS
    build_script:
      - git clone https://github.com/flutter/flutter.git -b stable
      - ./flutter/bin/flutter channel master
      - ./flutter/bin/flutter config --enable-macos-desktop
      - sudo gem install cocoapods
      - ./flutter/bin/flutter doctor
      - ./flutter/bin/flutter pub get
      - ./flutter/bin/flutter build macos
      - cd build/macos/Build/Products/Release
      - npm install --global create-dmg
      - create-dmg ./sample_project.app
      - ls -l
