image:
  - Visual Studio 2019
  - macOS

for:
  - matrix:
      only:
        - image: Visual Studio 2019
    build_script:
      - cmd: git clone https://github.com/flutter/flutter.git -b stable
      - cmd: ./flutter/bin/flutter channel master
      - cmd: ./flutter/bin/flutter upgrade
      - cmd: ./flutter/bin/flutter config --enable-windows-desktop
      - cmd: ./flutter/bin/flutter doctor
      - cmd: ./flutter/bin/flutter build windows
      - cmd: echo "Everything was built during the install step."
      - cmd: cd build
      - cmd: dir /s
  - matrix:
      only:
        - image: macOS
    build_script:
      - echo "I'm on macOS"
      - ls -l

#for:
#
#  -
#    matrix:
#      only:
#        - job_name: <job name 1>
#        [- job_group: <job name 1>] # optionally, you can define the configuration for the entire group
#
#    build_script:
#      - echo Job 1
#
#  -
#    matrix:
#      only:
#        - job_name: <job name 2>
#
#    build_script:
#      - echo Job 2
#
#  ...
